### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by kingjr** [lescientifik/tcia_downloader#1]
Hi, thanks for this package,

I'm trying to dowload NBIA data with a specific manifest (https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI), without luck sofar. 

Any chance you could make an API example to help me out?

Thank you very much!

**Comment by lescientifik** [comment]
Hi, thanks for your question.

I have added a very short Readme that will most likely be helpful. If not, please tell me what's your problem and i will try my best to solve it!

**Comment by kingjr** [comment]
Thanks for the prompt response. It works (but it doesn't create the same structure as the one generated by their software. )

**Comment by lescientifik** [comment]
Yes indeed, i should have mentionned it in the docs!
Nonetheless, if you go through the source code you will find some rudimentary code to classify and convert .dcm to nifti based on the metadatas of the dcm files. It is not for now accessible to the command line because this code doesn't (yet) support RT struct dicom file (as SimpleITK doesn't support it).

If you need that kind of functionnality, a good starter is also the dcm2niix project.

**Comment by kingjr** [comment]
Thanks !
